services:
  backend:
    container_name: blobsy-ws
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9933:9933"
    volumes:
      - ./backend/output:/app/output
      - ./backend/assets:/app/assets
      - ./backend/logs:/app/logs
      - ./backend/.env:/app/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9933/blob-info-history"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  frontend:
    container_name: blobsy-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend